/**
 * Client-side encryption for CipherRoom.
 *
 * Identity: ECDH P-256 key pair generated in-browser. Private key never leaves the device.
 * Room key: AES-256-GCM generated by the first participant who is ready.
 * Distribution: room key is wrapped to each peer using an ECDH-derived AES-GCM key.
 * Messages/files: AES-256-GCM with a random 12-byte IV per encryption.
 *
 * The server only relays opaque ciphertext, public keys, and wrapped keys.
 */

const ECDH_PARAMS: EcdhKeyGenParams = { name: 'ECDH', namedCurve: 'P-256' };
const AES_PARAMS: AesDerivedKeyParams = { name: 'AES-GCM', length: 256 };

export function bytesToB64(buf: ArrayBuffer | Uint8Array): string {
  const bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
  let binary = '';
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

export function b64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

export async function generateIdentity(): Promise<CryptoKeyPair> {
  return crypto.subtle.generateKey(ECDH_PARAMS, true, ['deriveKey', 'deriveBits']);
}

export async function exportPublicKey(pair: CryptoKeyPair): Promise<string> {
  const spki = await crypto.subtle.exportKey('spki', pair.publicKey);
  return bytesToB64(spki);
}

export async function importPublicKey(b64: string): Promise<CryptoKey> {
  return crypto.subtle.importKey('spki', b64ToBytes(b64), ECDH_PARAMS, true, []);
}

export async function generateRoomKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, ['encrypt', 'decrypt']);
}

async function deriveWrapKey(privateKey: CryptoKey, publicKey: CryptoKey): Promise<CryptoKey> {
  return crypto.subtle.deriveKey(
    { name: 'ECDH', public: publicKey },
    privateKey,
    AES_PARAMS,
    false,
    ['encrypt', 'decrypt'],
  );
}

export async function wrapRoomKey(
  roomKey: CryptoKey,
  myPrivate: CryptoKey,
  theirPublic: CryptoKey,
): Promise<{ wrappedKey: string; iv: string }> {
  const wrapKey = await deriveWrapKey(myPrivate, theirPublic);
  const raw = await crypto.subtle.exportKey('raw', roomKey);
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, wrapKey, raw);
  return { wrappedKey: bytesToB64(ct), iv: bytesToB64(iv) };
}

export async function unwrapRoomKey(
  wrappedKey: string,
  iv: string,
  myPrivate: CryptoKey,
  senderPublic: CryptoKey,
): Promise<CryptoKey> {
  const wrapKey = await deriveWrapKey(myPrivate, senderPublic);
  const raw = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: b64ToBytes(iv) },
    wrapKey,
    b64ToBytes(wrappedKey),
  );
  return crypto.subtle.importKey('raw', raw, { name: 'AES-GCM' }, true, ['encrypt', 'decrypt']);
}

export async function encryptText(
  roomKey: CryptoKey,
  plaintext: string,
): Promise<{ ciphertext: string; iv: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const data = new TextEncoder().encode(plaintext);
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, roomKey, data);
  return { ciphertext: bytesToB64(ct), iv: bytesToB64(iv) };
}

export async function decryptText(roomKey: CryptoKey, ciphertext: string, iv: string): Promise<string> {
  const pt = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: b64ToBytes(iv) },
    roomKey,
    b64ToBytes(ciphertext),
  );
  return new TextDecoder().decode(pt);
}

export async function encryptBytes(
  roomKey: CryptoKey,
  data: ArrayBuffer,
): Promise<{ ciphertext: ArrayBuffer; iv: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, roomKey, data);
  return { ciphertext: ct, iv: bytesToB64(iv) };
}

export async function decryptBytes(
  roomKey: CryptoKey,
  ciphertext: ArrayBuffer,
  iv: string,
): Promise<ArrayBuffer> {
  return crypto.subtle.decrypt({ name: 'AES-GCM', iv: b64ToBytes(iv) }, roomKey, ciphertext);
}

export class RoomCrypto {
  identity: CryptoKeyPair | null = null;
  publicKeyB64: string | null = null;
  roomKey: CryptoKey | null = null;
  peerKeys = new Map<string, CryptoKey>();
  wrappedFor = new Set<string>();
  ready = false;

  async init(): Promise<void> {
    this.identity = await generateIdentity();
    this.publicKeyB64 = await exportPublicKey(this.identity);
  }

  async becomeKeyHolder(): Promise<void> {
    if (this.roomKey) return;
    this.roomKey = await generateRoomKey();
    this.ready = true;
  }

  async addPeerPublicKey(peerId: string, spkiB64: string): Promise<void> {
    const key = await importPublicKey(spkiB64);
    this.peerKeys.set(peerId, key);
  }

  async wrapForPeer(peerId: string): Promise<{ wrappedKey: string; iv: string; senderPublicKey: string } | null> {
    if (!this.roomKey || !this.identity || !this.publicKeyB64) return null;
    const their = this.peerKeys.get(peerId);
    if (!their) return null;
    const wrapped = await wrapRoomKey(this.roomKey, this.identity.privateKey, their);
    this.wrappedFor.add(peerId);
    return { ...wrapped, senderPublicKey: this.publicKeyB64 };
  }

  async acceptWrappedKey(wrappedKey: string, iv: string, senderPublicKey: string): Promise<void> {
    if (!this.identity) throw new Error('crypto not ready');
    const sender = await importPublicKey(senderPublicKey);
    this.roomKey = await unwrapRoomKey(wrappedKey, iv, this.identity.privateKey, sender);
    this.ready = true;
  }

  async encrypt(text: string) {
    if (!this.roomKey) throw new Error('no room key');
    return encryptText(this.roomKey, text);
  }

  async decrypt(ciphertext: string, iv: string) {
    if (!this.roomKey) throw new Error('no room key');
    return decryptText(this.roomKey, ciphertext, iv);
  }

  async encryptFile(buf: ArrayBuffer) {
    if (!this.roomKey) throw new Error('no room key');
    return encryptBytes(this.roomKey, buf);
  }

  async decryptFile(buf: ArrayBuffer, iv: string) {
    if (!this.roomKey) throw new Error('no room key');
    return decryptBytes(this.roomKey, buf, iv);
  }

  destroy(): void {
    this.identity = null;
    this.publicKeyB64 = null;
    this.roomKey = null;
    this.peerKeys.clear();
    this.wrappedFor.clear();
    this.ready = false;
  }
}
